# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: off
