name: "Pull Request Docs Check"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  appstore_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install poetry
      run: |
        pip install "urllib3<2"
        pip install poetry==1.4.2

    - name: Install dependencies
      run: poetry install --with docs

    - name: Build docs
      run: make docs

    - name: Pack  the results in local tar file
      shell: bash
      run: tar czf /tmp/documentation.tar.gz -C docs/_build/html .

    - name: Upload static documentation
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Appstore docs.zip
        path: "/tmp/documentation.tar.gz"
